// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonelSistemi.Models;

#nullable disable

namespace PersonelSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512082247_CinsiyetEklendi")]
    partial class CinsiyetEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtekSistem.Models.Insaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurumId")
                        .HasColumnType("integer");

                    b.Property<string>("InsaatAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsaatTuru")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("KoordinatX")
                        .HasColumnType("double precision");

                    b.Property<double>("KoordinatY")
                        .HasColumnType("double precision");

                    b.Property<int>("TamamlanmaYuzdesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DurumId");

                    b.ToTable("Insaatlar");
                });

            modelBuilder.Entity("PersonelSistemi.Models.BPersonel", b =>
                {
                    b.Property<int>("objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("objectid"));

                    b.Property<string>("adi")
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.Property<string>("cinsiyet")
                        .HasColumnType("text")
                        .HasColumnName("cinsiyet");

                    b.Property<string>("sicil_no")
                        .HasColumnType("text")
                        .HasColumnName("sicil_no");

                    b.Property<string>("soyadi")
                        .HasColumnType("text")
                        .HasColumnName("soyadi");

                    b.Property<string>("tc")
                        .HasColumnType("text")
                        .HasColumnName("tc");

                    b.HasKey("objectid");

                    b.ToTable("b_personelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.InsaatBPersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BPersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("InsaatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BPersonelId");

                    b.HasIndex("InsaatId");

                    b.ToTable("InsaatBPersonelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.InsaatDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DurumAdi")
                        .HasColumnType("text")
                        .HasColumnName("durum_adi");

                    b.Property<string>("RenkKodu")
                        .HasColumnType("text")
                        .HasColumnName("renk_kodu");

                    b.HasKey("Id");

                    b.ToTable("InsaatDurumlari");
                });

            modelBuilder.Entity("PersonelSistemi.Models.InsaatPersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsaatId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsaatId");

                    b.HasIndex("PersonelId");

                    b.ToTable("InsaatPersonelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Konteyner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Boylam")
                        .HasColumnType("double precision");

                    b.Property<double>("Enlem")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Konteynerler");
                });

            modelBuilder.Entity("PersonelSistemi.Models.KonteynerAPersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KonteynerId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KonteynerId");

                    b.HasIndex("PersonelId");

                    b.ToTable("KonteynerAPersoneller");
                });

            modelBuilder.Entity("PersonelSistemi.Models.KonteynerBPersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BPersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("KonteynerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BPersonelId");

                    b.HasIndex("KonteynerId");

                    b.ToTable("KonteynerBPersoneller");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Personel", b =>
                {
                    b.Property<int>("objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("objectid"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.Property<string>("cinsiyet")
                        .HasColumnType("text")
                        .HasColumnName("cinsiyet");

                    b.Property<string>("personel_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personel_id");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soyadi");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tc");

                    b.HasKey("objectid");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("OtekSistem.Models.Insaat", b =>
                {
                    b.HasOne("PersonelSistemi.Models.InsaatDurumu", "InsaatDurumu")
                        .WithMany()
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsaatDurumu");
                });

            modelBuilder.Entity("PersonelSistemi.Models.InsaatBPersonel", b =>
                {
                    b.HasOne("PersonelSistemi.Models.BPersonel", "BPersonel")
                        .WithMany("InsaatBPersonelleri")
                        .HasForeignKey("BPersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtekSistem.Models.Insaat", "Insaat")
                        .WithMany("InsaatBPersonelleri")
                        .HasForeignKey("InsaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BPersonel");

                    b.Navigation("Insaat");
                });

            modelBuilder.Entity("PersonelSistemi.Models.InsaatPersonel", b =>
                {
                    b.HasOne("OtekSistem.Models.Insaat", "Insaat")
                        .WithMany("InsaatPersonelleri")
                        .HasForeignKey("InsaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelSistemi.Models.Personel", "Personel")
                        .WithMany("InsaatPersonelleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insaat");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelSistemi.Models.KonteynerAPersonel", b =>
                {
                    b.HasOne("PersonelSistemi.Models.Konteyner", "Konteyner")
                        .WithMany("KonteynerAPersoneller")
                        .HasForeignKey("KonteynerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelSistemi.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konteyner");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelSistemi.Models.KonteynerBPersonel", b =>
                {
                    b.HasOne("PersonelSistemi.Models.BPersonel", "BPersonel")
                        .WithMany()
                        .HasForeignKey("BPersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelSistemi.Models.Konteyner", "Konteyner")
                        .WithMany("KonteynerBPersoneller")
                        .HasForeignKey("KonteynerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BPersonel");

                    b.Navigation("Konteyner");
                });

            modelBuilder.Entity("OtekSistem.Models.Insaat", b =>
                {
                    b.Navigation("InsaatBPersonelleri");

                    b.Navigation("InsaatPersonelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.BPersonel", b =>
                {
                    b.Navigation("InsaatBPersonelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Konteyner", b =>
                {
                    b.Navigation("KonteynerAPersoneller");

                    b.Navigation("KonteynerBPersoneller");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Personel", b =>
                {
                    b.Navigation("InsaatPersonelleri");
                });
#pragma warning restore 612, 618
        }
    }
}
