// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonelSistemi.Models;

#nullable disable

namespace PersonelSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonelSistemi.Models.BPersonel", b =>
                {
                    b.Property<int>("objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("objectid"));

                    b.Property<string>("adi")
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.Property<string>("sicil_no")
                        .HasColumnType("text")
                        .HasColumnName("sicil_no");

                    b.Property<string>("soyadi")
                        .HasColumnType("text")
                        .HasColumnName("soyadi");

                    b.Property<string>("tc")
                        .HasColumnType("text")
                        .HasColumnName("tc");

                    b.HasKey("objectid");

                    b.ToTable("b_personelleri");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PersonelSistemi.Models.Personel", b =>
                {
                    b.Property<int>("objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("objectid"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.Property<string>("personel_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personel_id");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soyadi");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tc");

                    b.HasKey("objectid");

                    b.ToTable("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
